services:
  db:
    image: mariadb:11.4
    container_name: twinliquors-db
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3307:3306"   # keep your changed host port
volumes:
  db_data:
