[tool.black]
line-length = 100
target-version = ["py312"]

# Ruff config (modern layout)
[tool.ruff]
line-length = 100

[tool.ruff.lint]
# What to check:
select = ["E", "F", "I", "UP", "N", "SIM"]
# Let Black handle line length:
ignore = ["E501"]

# Ruff will sort imports (isort replacement)
[tool.ruff.lint.isort]
# (optional) tell Ruff your own packages so they’re grouped as first-party
# known-first-party = ["app"]

[tool.mypy]
python_version = "3.12"
strict_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = true
no_implicit_optional = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
