name: Quality checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11
        ports:
          - 3307:3306
        env:
          MARIADB_ROOT_PASSWORD: changeme-root-pass-123
          MARIADB_DATABASE: twinliquors
          MARIADB_USER: tlapp
          MARIADB_PASSWORD: changeme-app-123
        options: >-
          --health-cmd="mariadb-admin ping -h127.0.0.1 -P3306 -uroot -pchangeme-root-pass-123 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install MariaDB client
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client

      - name: Test DB connection
        run: |
          echo "Waiting for DB to be ready..."
          for i in {1..5}; do
            mariadb -h127.0.0.1 -P3307 -utlapp -pchangeme-app-123 twinliquors -e "SELECT 1;" && break
            echo "DB not ready yet... retrying ($i/5)"
            sleep 5
          done

      - name: Run Python tests
        run: |
          python -m unittest discover -s tests
